#!/bin/bash -x

export DEV=$HOME/Developer

rmln() {
  if [ -z "$2" ]; then
    rm ~/.$1 &> /dev/null
    ln -s {$DEV/Dotfiles/,~/.}$1
  else
    rm -r ~/$2 &> /dev/null
    ln -s $DEV/Dotfiles/$1 ~/$2
  fi
}

rmln bash_alias
rmln bash_path
rmln bash_vars
rmln bashrc
rmln gitconfig
rmln gitignore
rmln inputrc
rmln vimrc
rmln tmux.conf

mkdir ~/.config
rmln {,.config/nvim/}init.lua
rmln {,.config/}karabiner
rmln {,.config/}zed/tasks.json

mkdir -p ~/.julia/config
rmln {,.julia/config/}startup.jl
